const menu = [
    {
      name: "Sweet and Sour Chicken",
      price: "$10.99",
      pieces: 6,
      calories: 420,
      type: ["chicken", "rice"],
      image: "../sweet_and_sour_chicken.jpg",
    },
    {
      name: "Mongolian Beef",
      price: "$12.99",
      pieces: 8,
      calories: 570,
      type: ["beef", "other"],
      image: "../mongolian_beef.jpg",
    },
    {
      name: "Kung Pao Chicken",
      price: "$9.99",
      pieces: 6,
      calories: 380,
      type: ["chicken", "rice"],
      image: "../kung_pao_chicken.jpg",
    },
    {
      name: "Shrimp Fried Rice",
      price: "$11.99",
      pieces: 1,
      calories: 620,
      type: ["rice", "shrimp"],
      image: "../shrimp_fried_rice.jpg",
    },
    {
      name: "General Tso's Chicken",
      price: "$11.99",
      pieces: 8,
      calories: 520,
      type: ["chicken", "other"],
      image: "../general_tso_chicken.jpg",
    },
    {
      name: "Egg Foo Young",
      price: "$8.99",
      pieces: 3,
      calories: 280,
      type: ["other"],
      image: "../egg_foo_young.jpg",
    },
    {
      name: "Spring Rolls",
      price: "$4.99",
      pieces: 3,
      calories: 200,
      type: ["beef", "rice"],
      image: "../shrimp_roll.jpg",
    },
    {
      name: "Hot and Sour Soup",
      price: "$5.99",
      pieces: 1,
      calories: 180,
      type: ["other"],
      image: "../hot_and_sour_soup.jpg",
    },
    {
      name: "Orange Chicken",
      price: "$10.99",
      pieces: 8,
      calories: 450,
      type: ["chicken", "other"],
      image: "../orange_chicken.jpg",
    },
    {
      name: "Beef and Broccoli",
      price: "$11.99",
      pieces: 6,
      calories: 380,
      type: ["beef", "rice"],
      image: "../beef_and_broccoli.jpg",
    },
    {
      name: "Crab Rangoon",
      price: "$6.99",
      pieces: 6,
      calories: 320,
      type: ["other", "rice"],
      image: "../crab_rangoon.jpg",
    },
    {
      name: "Sesame Chicken",
      price: "$10.99",
      pieces: 8,
      calories: 500,
      type: ["chicken", "rice"],
      image: "../sesame_chicken.jpg",
    },
    {
      name: "Steamed Dumplings",
      price: "$7.99",
      pieces: 6,
      calories: 250,
      type: ["other", "shrimp"],
      image: "../steamed_dumplings.jpg",
    },
    {
      name: "Fried Wontons",
      price: "$6.99",
      pieces: 8,
      calories: 320,
      type: ["other", "beef"],
      image: "../fried_wonton.jpg",
    },
    {
      name: "General Tso's Tofu",
      price: "$9.99",
      pieces: 6,
      calories: 450,
      type: ["other"],
      image: "../general_tso_tofu.jpg",
    },
    {
      name: "Pepper Steak",
      price: "$11.99",
      pieces: 6,
      calories: 420,
      type: ["beef", "other"],
      image: "../pepper_steak.jpg",
    },
    {
      name: "Honey Walnut Shrimp",
      price: "$12.99",
      pieces: 8,
      calories: 550,
      type: ["shrimp", "other"],
      image: "../honey_walnut_shrimp.jpg",
    },
    {
      name: "Wonton Soup",
      price: "$5.99",
      pieces: 1,
      calories: 150,
      type: ["beef", "noodle"],
      image: "../wonton_soup.jpg",
    },
    {
      name: "Moo Goo Gai Pan",
      price: "$10.99",
      pieces: 6,
      calories: 350,
      type: ["rice", "chicken"],
      image: "../moo_goo_gai_pan.jpg",
    },
    {
      name: "Shrimp Lo Mein",
      price: "$12.99",
      pieces: 1,
      calories: 680,
      type: ["shrimp", "noodle"],
      image: "../shrimp_lo_mein.jpg",
    },
    {
      name: "Cashew Chicken",
      price: "$10.99",
      pieces: 6,
      calories: 420,
      type: ["chicken", "other"],
      image: "../cashew_chicken.jpg",
    },
    {
      name: "Chicken Chow Mein",
      price: "$9.99",
      pieces: 1,
      calories: 600,
      type: ["chicken", "noodle"],
      image: "../chicken_chow_mein.jpg",
    },
    {
      name: "Szechuan Tofu",
      price: "$9.99",
      pieces: 6,
      calories: 320,
      type: ["tofu", "noodle"],
      image: "../schezwan_tofu.jpg",
    },
    {
      name: "Egg Drop Soup",
      price: "$4.99",
      pieces: 1,
      calories: 130,
      type: ["other"],
      image: "../egg_drop_soup.jpg",
    },
    {
      name: "Salt and Pepper Shrimp",
      price: "$13.99",
      pieces: 8,
      calories: 580,
      type: ["shrimp", "other"],
      image: "../salt_and_pepper_shrimp.jpg",
    },
    {
      name: "Beef Chow Fun",
      price: "$11.99",
      pieces: 1,
      calories: 690,
      type: ["beef", "noodle"],
      image: "../beef_chow_fun.jpg",
    },
    {
      name: "Hot and Spicy Tofu",
      price: "$9.99",
      pieces: 6,
      calories: 380,
      type: ["other"],
      image: "../hot_and_spicy_tofu.jpg",
    },
  ];

export { menu };
