const menu = [
    {
      name: "Sweet and Sour Chicken",
      price: "$10.99",
      pieces: 6,
      calories: 420,
      type: ["chicken"],
      image: "",
    },
    {
      name: "Mongolian Beef",
      price: "$12.99",
      pieces: 8,
      calories: 570,
      type: ["beef"],
      image: "",
    },
    {
      name: "Kung Pao Chicken",
      price: "$9.99",
      pieces: 6,
      calories: 380,
      type: ["chicken"],
      image: "",
    },
    {
      name: "Shrimp Fried Rice",
      price: "$11.99",
      pieces: 1,
      calories: 620,
      type: ["other", "shrimp"],
      image: "",
    },
    {
      name: "General Tso's Chicken",
      price: "$11.99",
      pieces: 8,
      calories: 520,
      type: ["chicken"],
      image: "",
    },
    {
      name: "Egg Foo Young",
      price: "$8.99",
      pieces: 3,
      calories: 280,
      type: ["other"],
      image: "",
    },
    {
      name: "Spring Rolls",
      price: "$4.99",
      pieces: 3,
      calories: 200,
      type: ["beef", "other"],
      image: "",
    },
    {
      name: "Hot and Sour Soup",
      price: "$5.99",
      pieces: 1,
      calories: 180,
      type: ["soup"],
      image: "",
    },
    {
      name: "Orange Chicken",
      price: "$10.99",
      pieces: 8,
      calories: 450,
      type: ["chicken"],
      image: "",
    },
    {
      name: "Beef and Broccoli",
      price: "$11.99",
      pieces: 6,
      calories: 380,
      type: ["beef", "other"],
      image: "",
    },
    {
      name: "Crab Rangoon",
      price: "$6.99",
      pieces: 6,
      calories: 320,
      type: ["other"],
      image: "",
    },
    {
      name: "Sesame Chicken",
      price: "$10.99",
      pieces: 8,
      calories: 500,
      type: ["chicken"],
      image: "",
    },
    {
      name: "Steamed Dumplings",
      price: "$7.99",
      pieces: 6,
      calories: 250,
      type: ["other"],
      image: "",
    },
    {
      name: "Fried Wontons",
      price: "$6.99",
      pieces: 8,
      calories: 320,
      type: ["other"],
      image: "",
    },
    {
      name: "General Tso's Tofu",
      price: "$9.99",
      pieces: 6,
      calories: 450,
      type: ["tofu"],
      image: "",
    },
    {
      name: "Pepper Steak",
      price: "$11.99",
      pieces: 6,
      calories: 420,
      type: ["beef"],
      image: "",
    },
    {
      name: "Honey Walnut Shrimp",
      price: "$12.99",
      pieces: 8,
      calories: 550,
      type: ["shrimp", "other"],
      image: "",
    },
    {
      name: "Wonton Soup",
      price: "$5.99",
      pieces: 1,
      calories: 150,
      type: ["soup"],
      image: "",
    },
    {
      name: "Moo Goo Gai Pan",
      price: "$10.99",
      pieces: 6,
      calories: 350,
      type: ["other", "chicken"],
      image: "",
    },
    {
      name: "Shrimp Lo Mein",
      price: "$12.99",
      pieces: 1,
      calories: 680,
      type: ["shrimp"],
      image: "",
    },
    {
      name: "Cashew Chicken",
      price: "$10.99",
      pieces: 6,
      calories: 420,
      type: ["chicken"],
      image: "",
    },
    {
      name: "Chicken Chow Mein",
      price: "$9.99",
      pieces: 1,
      calories: 600,
      type: ["chicken"],
      image: "",
    },
    {
      name: "Szechuan Tofu",
      price: "$9.99",
      pieces: 6,
      calories: 320,
      type: ["tofu"],
      image: "",
    },
    {
      name: "Egg Drop Soup",
      price: "$4.99",
      pieces: 1,
      calories: 130,
      type: ["soup"],
      image: "",
    },
    {
      name: "Salt and Pepper Shrimp",
      price: "$13.99",
      pieces: 8,
      calories: 580,
      type: ["shrimp"],
      image: "",
    },
    {
      name: "Beef Chow Fun",
      price: "$11.99",
      pieces: 1,
      calories: 690,
      type: ["beef"],
      image: "",
    },
    {
      name: "Hot and Spicy Tofu",
      price: "$9.99",
      pieces: 6,
      calories: 380,
      type: ["tofu"],
      image: "",
    },
  ];

export { menu };
